### ISSUE TITLE
jvm chaosd throw exception  `AttachNotSupportedException`

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#57]
Use chaosd attach agent to java process, and get a error:

```log
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
```

Java version: v1.8.0

**Comment by WangXiangUSTC** [comment]
The class that could not be found is in tools.jar in JDK 1.8, so need to specify the classpath. Need to update the `byteman/bin/bminstall.sh`,  add one line before the last java command:

```bash
CP=$JAVA_HOME/lib/tools.jar:$CP
```
